#!/usr/bin/python
from bs4 import BeautifulSoup
import os, sys

Home 		= 'http://www.geeksforgeeks.org/'
Extensions 	= {'cpp':'.cpp', 'java':'.java', 'python':'.py'}

def HorizontalBreak(Number):
	Line = '*'*Number
	print Line

def GetExtension(pre):
	for key in Extensions.keys():
		if key in pre:
			return Extensions[key]

def DisplayCodeHeadings(pres):
	preCodes 	= ['+']
	UnwantedCJava	= ['//', '/*', '*/']
	SNo		= 1
	print 'type numbers: [1 2 .. to save the code] or [* to save all the codes] or [0 to exit]'
	for pre in pres:
		if "brush: cpp" in str(pre):
			preCodes.append(pre)
			pre  = pre.text.splitlines()
			heading = ''
			for line in pre:
				if '//' in line or '/*' in line:
					heading += line
				if line.startswith('#include') or line.startswith('# include'):
					break
			for u in UnwantedCJava:
				heading = heading.replace(u, '')
			print str(SNo) + ') (cpp)' + heading
			SNo += 1
		elif "brush: java" in str(pre):
			preCodes.append(pre)
                        pre  = pre.text.splitlines()
                        heading = ''
                        for line in pre:
                                if '//' in line or '/*' in line:
                                        heading += line
                                if line.startswith('import') or line.startswith('class'):
                                        break
                        for u in UnwantedCJava:
                                heading = heading.replace(u, '')
                        print str(SNo) + ') (java)' + heading
                        SNo += 1
		elif "brush: python" in str(pre):
			preCodes.append(pre)
                        pre  = pre.text.splitlines()
                        heading = ''
                        for line in pre:
                                if '#' in line:
					heading += line
                                if line.startswith('def'):
                                        break
			heading = heading.replace('#', '')
                        print str(SNo) + ') (python)' + heading
                        SNo += 1
	return preCodes	

def DisplayContent(URL, StoreFlag):
	os.system('curl -s -o .page.html "' + URL + '"')
	Page	= open('./.page.html')
	Soup	= BeautifulSoup(Page, 'html.parser')
	pres	= Soup.find_all('pre')
	FileName= URL[len(Home):].replace('/', '')
	i	= 1
	NoCode	= 1
	if StoreFlag == 1:
		preCodes = DisplayCodeHeadings(pres)
		if len(preCodes) > 1:
			NoCode  = 0
			Numbers = raw_input('> ').split()
			if '0' in Numbers:
				print 'Bye!'
				exit()
			if '*' in Numbers:
				Numbers = list(range(1, len(preCodes)))
			else:
				Numbers = map(int, Numbers)
			for Number in Numbers:
				Code = preCodes[Number].text.replace('\r', '')
				TempFileName = str(FileName) + '-' + str(i) + GetExtension(str(preCodes[Number]))
				i += 1
				with open(TempFileName, 'w') as Temp:
					Temp.write(Code)
				print 'Saved ' + str(Number) + ' as => ' + TempFileName
	if StoreFlag == 0:
		for pre in pres:
			if "brush" in str(pre):
				NoCode 	= 0
				Code  	= pre.text.replace('\r', '')
				print Code
				HorizontalBreak(65)
	if NoCode == 1:
		print 'Enter a link with code!'
	if StoreFlag == 1:
		print 'Download Successful!'
	os.system('rm .page.html')

if __name__ == '__main__':
	if len(sys.argv) >= 2:
		StoreFlag = 0
		if len(sys.argv) == 3:
			if sys.argv[2] == '--store':
				StoreFlag = 1
			else:
				print 'Invalid Command!'
		if Home in sys.argv[1]:
			DisplayContent(sys.argv[1], StoreFlag)
		else:
			print "I've been programmed to work only for " + Home
	else:
		print 'Better Luck Next Time'
